import { Link } from '@tanstack/react-router';
import { ArrowUpRight } from 'lucide-react';
import { Hero } from './hero';
import { MatchCard } from '@/features/league/match-card';
import { LeagueTable } from '@/features/league/league-table';
import { nextMatch, latestResult } from '@/data/matches';
import { news } from '@/data/news';
import { NewsCard } from '@/features/news/news-card';
import { assets } from '@/config/assets';
function SectionLink({ to, children }: { to: '/league' | '/news' | '/about'; children: React.ReactNode }) { return <Link to={to} className="inline-flex items-center gap-2 border-b border-copper pb-1 text-xs font-bold uppercase tracking-wider text-copper transition-colors hover:text-foreground">{children}<ArrowUpRight size={16}/></Link>; }
export function HomePage() { return <><Hero/><section className="border-b border-border bg-card"><div className="site-container grid lg:grid-cols-2"><div className="border-b border-border py-14 lg:border-b-0 lg:border-r lg:pr-12"><div className="flex items-end justify-between gap-3"><div><p className="eyebrow text-primary">01 / The next 90</p><h2 className="mt-3 font-display text-5xl font-bold uppercase md:text-6xl">Next match</h2></div><SectionLink to="/league">All fixtures</SectionLink></div><div className="mt-7"><MatchCard match={nextMatch} compact/></div></div><div className="py-14 lg:pl-12"><div className="flex items-end justify-between gap-3"><div><p className="eyebrow text-copper">02 / Last whistle</p><h2 className="mt-3 font-display text-5xl font-bold uppercase md:text-6xl">Latest result</h2></div><SectionLink to="/league">Results</SectionLink></div><div className="mt-7"><MatchCard match={latestResult} compact/></div></div></div></section><section className="site-container grid gap-12 py-20 lg:grid-cols-[.8fr_1.2fr] lg:gap-24 lg:py-28"><div><p className="eyebrow text-primary">03 / The standings</p><h2 className="section-title mt-5">The race<br/>is on.</h2><p className="mt-7 max-w-sm leading-relaxed text-muted-foreground">Every point matters. Follow the club’s place in the FLA League as the season unfolds.</p><div className="mt-8"><SectionLink to="/league">Full league table</SectionLink></div></div><div className="min-w-0 self-center"><LeagueTable compact /></div></section><section className="relative min-h-[530px] overflow-hidden border-y border-border"><img src={assets.training} alt="Players training on a football pitch at dusk" width={1280} height={896} loading="lazy" className="absolute inset-0 h-full w-full object-cover object-center"/><div className="absolute inset-0 bg-background/60"/><div className="site-container relative flex min-h-[530px] flex-col justify-end py-16"><p className="eyebrow text-copper">More than a game</p><h2 className="section-title mt-5 max-w-3xl">A shared city.<br/>A shared passion.</h2><p className="mt-6 max-w-xl text-foreground/85">Built around a love of football and the connections it creates.</p><div className="mt-7"><SectionLink to="/about">Our story</SectionLink></div></div></section><section className="site-container py-20 lg:py-28"><div className="mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow text-primary">04 / Around the club</p><h2 className="section-title mt-4">Latest news</h2></div><SectionLink to="/news">All stories</SectionLink></div><div className="grid gap-7 md:grid-cols-3">{news.slice(0,3).map(item => <NewsCard key={item.id} item={item}/>)}</div></section></>; }
