"""initial club schema"""

import sqlalchemy as sa
from alembic import op

revision = "88d3376a7ebf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competition_seasons",
        sa.Column("fla_championship_id", sa.Integer(), nullable=False),
        sa.Column("fla_season_id", sa.Integer(), nullable=False),
        sa.Column("competition_name", sa.String(length=200), nullable=False),
        sa.Column("division", sa.String(length=100), nullable=False),
        sa.Column("season_label", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fla_championship_id", "fla_season_id"),
    )
    op.create_table(
        "contact_messages",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "players",
        sa.Column("display_name", sa.String(length=150), nullable=False),
        sa.Column("photo_url", sa.Text(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_runs",
        sa.Column("dataset", sa.String(length=30), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("inserted_count", sa.Integer(), nullable=False),
        sa.Column("updated_count", sa.Integer(), nullable=False),
        sa.Column("error_summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("fla_team_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("logo_url", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fla_team_id"),
    )
    op.create_table(
        "users",
        sa.Column("normalized_email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("normalized_email"),
    )
    op.create_table(
        "venues",
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "address"),
    )
    op.create_table(
        "account_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_account_tokens_user_id"), "account_tokens", ["user_id"], unique=False)
    op.create_table(
        "matches",
        sa.Column("competition_season_id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=200), nullable=False),
        sa.Column("home_team_id", sa.Uuid(), nullable=False),
        sa.Column("away_team_id", sa.Uuid(), nullable=False),
        sa.Column("venue_id", sa.Uuid(), nullable=True),
        sa.Column("matchday", sa.Integer(), nullable=False),
        sa.Column("leg", sa.String(length=20), nullable=False),
        sa.Column("kickoff_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("status <> 'final' OR home_score IS NOT NULL", name="final_has_score"),
        sa.CheckConstraint(
            "status IN ('scheduled','final','postponed','cancelled','unknown')", name="match_status"
        ),
        sa.CheckConstraint("(home_score IS NULL) = (away_score IS NULL)", name="paired_scores"),
        sa.CheckConstraint("away_score IS NULL OR away_score >= 0", name="away_score_nonnegative"),
        sa.CheckConstraint("home_score IS NULL OR home_score >= 0", name="home_score_nonnegative"),
        sa.CheckConstraint("home_team_id <> away_team_id", name="different_teams"),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["competition_season_id"],
            ["competition_seasons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["venue_id"],
            ["venues.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("competition_season_id", "source_key"),
    )
    op.create_index(op.f("ix_matches_away_team_id"), "matches", ["away_team_id"], unique=False)
    op.create_index(
        "ix_matches_competition_kickoff",
        "matches",
        ["competition_season_id", "kickoff_at"],
        unique=False,
    )
    op.create_index(op.f("ix_matches_home_team_id"), "matches", ["home_team_id"], unique=False)
    op.create_index(op.f("ix_matches_venue_id"), "matches", ["venue_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "squad_memberships",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("season_label", sa.String(length=20), nullable=False),
        sa.Column("shirt_number", sa.Integer(), nullable=True),
        sa.Column("position", sa.String(length=30), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "position IN ('Goalkeepers','Defenders','Midfielders','Forwards')",
            name="player_position",
        ),
        sa.CheckConstraint("shirt_number IS NULL OR shirt_number > 0", name="shirt_positive"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "season_label"),
        sa.UniqueConstraint("season_label", "shirt_number"),
    )
    op.create_index(
        op.f("ix_squad_memberships_player_id"), "squad_memberships", ["player_id"], unique=False
    )
    op.create_table(
        "standings_snapshots",
        sa.Column("competition_season_id", sa.Uuid(), nullable=False),
        sa.Column("sync_run_id", sa.Uuid(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["competition_season_id"],
            ["competition_seasons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sync_run_id"],
            ["sync_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_standings_snapshots_competition_season_id"),
        "standings_snapshots",
        ["competition_season_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_standings_snapshots_fetched_at"),
        "standings_snapshots",
        ["fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_standings_snapshots_sync_run_id"),
        "standings_snapshots",
        ["sync_run_id"],
        unique=False,
    )
    op.create_table(
        "match_videos",
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("status IN ('pending','ready','failed')", name="video_status"),
        sa.CheckConstraint("size_bytes > 0", name="video_size_positive"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(
        op.f("ix_match_videos_uploaded_by"), "match_videos", ["uploaded_by"], unique=False
    )
    op.create_index("ix_video_match_status", "match_videos", ["match_id", "status"], unique=False)
    op.create_table(
        "standings_rows",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("played", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("draws", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("goal_difference", sa.Integer(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.CheckConstraint("played = wins + draws + losses", name="played_total"),
        sa.CheckConstraint(
            "position > 0 AND played >= 0 AND wins >= 0 AND draws >= 0 AND losses >= 0",
            name="valid_standing_counts",
        ),
        sa.ForeignKeyConstraint(["snapshot_id"], ["standings_snapshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "team_id"),
        sa.UniqueConstraint("snapshot_id", "position"),
    )
    op.create_index(op.f("ix_standings_rows_team_id"), "standings_rows", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_standings_rows_team_id"), table_name="standings_rows")
    op.drop_table("standings_rows")
    op.drop_index("ix_video_match_status", table_name="match_videos")
    op.drop_index(op.f("ix_match_videos_uploaded_by"), table_name="match_videos")
    op.drop_table("match_videos")
    op.drop_index(op.f("ix_standings_snapshots_sync_run_id"), table_name="standings_snapshots")
    op.drop_index(op.f("ix_standings_snapshots_fetched_at"), table_name="standings_snapshots")
    op.drop_index(
        op.f("ix_standings_snapshots_competition_season_id"), table_name="standings_snapshots"
    )
    op.drop_table("standings_snapshots")
    op.drop_index(op.f("ix_squad_memberships_player_id"), table_name="squad_memberships")
    op.drop_table("squad_memberships")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_matches_venue_id"), table_name="matches")
    op.drop_index(op.f("ix_matches_home_team_id"), table_name="matches")
    op.drop_index("ix_matches_competition_kickoff", table_name="matches")
    op.drop_index(op.f("ix_matches_away_team_id"), table_name="matches")
    op.drop_table("matches")
    op.drop_index(op.f("ix_account_tokens_user_id"), table_name="account_tokens")
    op.drop_table("account_tokens")
    op.drop_table("venues")
    op.drop_table("users")
    op.drop_table("teams")
    op.drop_table("sync_runs")
    op.drop_table("players")
    op.drop_table("contact_messages")
    op.drop_table("competition_seasons")
    # ### end Alembic commands ###
