"""Allow linked match highlights"""

import sqlalchemy as sa
from alembic import op

revision = "bac727c65584"
down_revision = "e2370a810101"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match_videos", sa.Column("video_url", sa.Text(), nullable=True))
    op.alter_column("match_videos", "uploaded_by", existing_type=sa.UUID(), nullable=True)
    op.alter_column("match_videos", "object_key", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "match_videos", "content_type", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("match_videos", "size_bytes", existing_type=sa.INTEGER(), nullable=True)
    op.create_unique_constraint("uq_match_video_url", "match_videos", ["match_id", "video_url"])
    op.create_check_constraint(
        "video_source",
        "match_videos",
        "(video_url IS NOT NULL AND object_key IS NULL) OR (video_url IS NULL AND object_key IS NOT NULL AND uploaded_by IS NOT NULL AND content_type IS NOT NULL AND size_bytes IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade():
    # Linked highlights cannot be represented by the old upload-only schema.
    # Fail without deleting data; an operator must migrate those records first.
    if (
        op.get_bind()
        .execute(sa.text("SELECT EXISTS (SELECT 1 FROM match_videos WHERE video_url IS NOT NULL)"))
        .scalar()
    ):
        raise RuntimeError("Migrate linked highlights before downgrading")
    op.drop_constraint("video_source", "match_videos", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_match_video_url", "match_videos", type_="unique")
    op.alter_column("match_videos", "size_bytes", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "match_videos", "content_type", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column("match_videos", "object_key", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("match_videos", "uploaded_by", existing_type=sa.UUID(), nullable=False)
    op.drop_column("match_videos", "video_url")
    # ### end Alembic commands ###
