"""Support cup competitions and unnumbered rounds"""

import sqlalchemy as sa
from alembic import op

revision = "d519dc376422"
down_revision = "88d3376a7ebf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("competition_seasons", sa.Column("fla_cup_id", sa.Integer(), nullable=True))
    op.alter_column(
        "competition_seasons", "fla_championship_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.create_unique_constraint(
        "uq_cup_season", "competition_seasons", ["fla_cup_id", "fla_season_id"]
    )
    op.alter_column("matches", "matchday", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "matches",
        "leg",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=200),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches",
        "leg",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    op.alter_column("matches", "matchday", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("uq_cup_season", "competition_seasons", type_="unique")
    op.alter_column(
        "competition_seasons", "fla_championship_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_column("competition_seasons", "fla_cup_id")
    # ### end Alembic commands ###
