"""add match goals"""

import sqlalchemy as sa
from alembic import op

revision = "f0ad5f64a5bd"
down_revision = "1a2b3c4d5e6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_goals",
        sa.Column("match_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("scorer_id", sa.Uuid(), nullable=True),
        sa.Column("assist_player_id", sa.Uuid(), nullable=True),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("stoppage_minute", sa.Integer(), nullable=True),
        sa.Column("goal_type", sa.String(length=20), server_default="regular", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "goal_type <> 'own_goal' OR assist_player_id IS NULL", name="own_goal_no_assist"
        ),
        sa.CheckConstraint("goal_type IN ('regular','penalty','own_goal')", name="goal_type_valid"),
        sa.CheckConstraint("minute IS NULL OR minute >= 0", name="goal_minute_valid"),
        sa.CheckConstraint("scorer_id <> assist_player_id", name="goal_different_players"),
        sa.CheckConstraint(
            "stoppage_minute IS NULL OR (minute IS NOT NULL AND stoppage_minute > 0)",
            name="goal_stoppage_valid",
        ),
        sa.ForeignKeyConstraint(["assist_player_id"], ["players.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scorer_id"], ["players.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_match_goals_assist_player_id"), "match_goals", ["assist_player_id"], unique=False
    )
    op.create_index(op.f("ix_match_goals_match_id"), "match_goals", ["match_id"], unique=False)
    op.create_index(op.f("ix_match_goals_scorer_id"), "match_goals", ["scorer_id"], unique=False)
    op.create_index(op.f("ix_match_goals_team_id"), "match_goals", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_goals_team_id"), table_name="match_goals")
    op.drop_index(op.f("ix_match_goals_scorer_id"), table_name="match_goals")
    op.drop_index(op.f("ix_match_goals_match_id"), table_name="match_goals")
    op.drop_index(op.f("ix_match_goals_assist_player_id"), table_name="match_goals")
    op.drop_table("match_goals")
    # ### end Alembic commands ###
